{{- if .Values.Bucket.enabled }}
---
apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: devxp-{{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.name }}
spec:
  forProvider:
    acl: private
    locationConstraint: us-east-1
    objectLockEnabledForBucket: false
  providerConfigRef:
    name: default
{{- end }}