---
# Source: devxp-app/templates/Namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: teste-loki
  labels:
    kubernetes.io/metadata.name: teste-loki
    backstage.io/kubernetes-id: teste-loki
spec:
  finalizers:
  - kubernetes
---
# Source: devxp-app/templates/ServiceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teste-loki
  namespace: teste-loki
---
# Source: devxp-app/templates/Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: teste-loki
  namespace: teste-loki
  annotations:
    external-dns.alpha.kubernetes.io/hostname: teste-loki.diegoluisi.eti.br
  labels:
    app: teste-loki
    version: b289a6c9
    backstage.io/kubernetes-id: teste-loki
spec:
  type: ClusterIP
  ports:
  - name: tcp-node
    port: 80
    targetPort:  8080
  selector:
    app: teste-loki
---
# Source: devxp-app/templates/Deployment.yaml
apiVersion: argoproj.io/v1alpha1
kind: Deployment
metadata:
  name: teste-loki
  namespace: teste-loki
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: teste-loki
  template:
    metadata:
      labels:
        app: teste-loki
        version: b289a6c9
        backstage.io/kubernetes-id: teste-loki
    spec:
      containers:
      - name: teste-loki
        image: ghcr.io/devxp-tech/teste-loki:b289a6c9
        imagePullPolicy: IfNotPresent
        env:
        envFrom:
        ports:
        - name: http
          containerPort: 8080
        resources: 
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector: 
        {}
      affinity: 
        {}
      tolerations: 
        []
  minReadySeconds: 30
---
# Source: devxp-app/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-devxp-app-test-connection"
  labels:
    helm.sh/chart: devxp-app-0.1.64
    app.kubernetes.io/name: devxp-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-devxp-app:']
  restartPolicy: Never
