name: teste-loki
image:
  repository: ghcr.io/devxp-tech/teste-loki
  tag: b289a6c9
  network:
    domain: diegoluisi.eti.br
    service:
      type: ClusterIP
deployment:
  enabled: true
sealedSecrets:
  enabled: false
quota:
  enabled: false
istioInjection:
  enabled: false
ingress:
  enabled: false
autoscaling:
  enabled: false
argoRollouts:
  enabled: false