name: teste-loki
image:
  repository: ghcr.io/devxp-tech/teste-loki
  tag: b289a6c9
  network:
    domain: diegoluisi.eti.br
    service:
      type: ClusterIP
sealedSecrets:
  enabled: false
quota:
  enabled: false
istioInjection: false
ingress:
  enabled: false
PeerAuthentication:
  enabled: false
autoscaling:
  enabled: false
livenessProbe:
  httpGet:
    path: /health-check/liveness
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /health-check/readiness
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
argoRollouts:
  enabled: false
deployment:
  enabled: true