---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.name }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Values.name }}
  minReplicas: 4
  maxReplicas: 8
  # targetCPUUtilizationPercentage: 80
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70