{{- if .Values.migration.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name }}-migration
  namespace: {{ include "namespace" . }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    sidecar.istio.io/inject: "false"
spec:
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
        - image: diegoluisi/{{ .Values.name }}-migraton:latest
          name: {{ .Values.name }}-migration
          command:
            - /bin/bash
            - -c
            - |
              echo N | liquibase \
              --url=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB} \
              --username=${POSTGRES_USER} \
              --password=${POSTGRES_PASSWORD} \
              --classpath=/liquibase/changelog \
              --changeLogFile=migrations.yaml update 
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
{{- end }}