---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "namespace" . }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.name }}
    backstage.io/kubernetes-id: {{ .Values.name }}
    {{- if .Values.istioInjection.enabled }}
    istio-injection: enabled
    {{- end }}
spec:
  finalizers:
  - kubernetes