---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.name }}
    backstage.io/kubernetes-id: {{ .Values.name }}
    istio-injection: enabled
spec:
  finalizers:
  - kubernetes