apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.name }}-strict
  namespace: istioinaction
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  mtls:
    mode: STRICT