apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ default 1 .Values.replicaCount }}
  {{- end }}
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Values.name }}        # required
            routes:
            - primary                 # required
          destinationRule:
            name: {{ .Values.name }}    # required
            canarySubsetName: canary    # required
            stableSubsetName: stable    # required
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 5
      - pause:
          duration: 10s
      - setWeight: 20
      - pause:
          duration: 10s
      - setWeight: 40
      - pause:
          duration: 10s
      - setWeight: 60
      - pause:
          duration: 10s
      - setWeight: 80
      - pause:
          duration: 10s
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.image.tag }}
        backstage.io/kubernetes-id: {{ .Values.name }}
    spec:
      {{- if not .Values.ServiceAccount.enabled }}
      serviceAccountName: {{ .Values.name }}
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: {{- include "env" . | nindent 12 }}
        envFrom: {{- include "env" . | nindent 12 }}
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            port: {{ .Values.port }}
            path: /health-check/readiness
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: {{ .Values.port }}
            path: /health-check/liveness
          initialDelaySeconds: 15
          periodSeconds: 10
        resources: {{ toYaml .Values.resources | nindent 12 }}
      nodeSelector: {{ toYaml (default dict .Values.nodeSelector) | nindent 8 }}
      affinity: {{ toYaml (default dict .Values.affinity) | nindent 8 }}
      tolerations: {{ toYaml (default list .Values.tolerations)  | nindent 8 }}
  minReadySeconds: 30
  revisionHistoryLimit: 3
