apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name:  {{ .Values.name }}
  annotations:
    # this is because the name is a deployment time parameter
    # consider also using "cluster-wide" if the namespace is also a parameter
    # please make sure you understand the implications, see README
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: {{- toYaml .Values.sealedSecrets | indent 1 }}
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      creationTimestamp: null