{{- if .Values.istioGateway.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateway-{{ .Values.global.application.cluster.name }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.istioGateway.namespace }}
    server: {{ .Values.global.application.cluster.server }}
  project: {{ .Values.global.application.project }}
  source:
    chart: gateway
    helm:
      valueFiles:
      - values.yaml
      {{- with .Values.istioGateway.values }}
      values: |-
      {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.14.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

{{- if .Values.istioGateway.gateways.public.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
  {{- with .Values.istioGateway.gateways.public.servers }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

{{- if .Values.istioGateway.gateways.private.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
  servers:
  - hosts:
    - "*"
    port:
      number: 80
      name: http
      protocol: HTTP
  {{- with .Values.istioGateway.gateways.private.servers }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

{{- end }}