name: teste-loki
image:
  repository: ghcr.io/analect-io/teste-loki
  tag: 0e43448a
network:
  service:
    type: NodePort
deployment:
  enabled: true
argoRollouts:
  enabled: false
sealedSecrets:
  enabled: false
quota:
  enabled: false
istioInjection:
  enabled: false
ingress:
  enabled: false
autoscaling:
  enabled: false